services:
  frontend-blue:
    image: ctrldaviddee/annuaire_did:${IMAGE_TAG:-latest}
    container_name: frontend-blue
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 20s
    networks:
      - annuaire_did_web

networks:
  annuaire_did_web:
    external: true
