services:
  nginx:
    image: nginx:1.28-alpine
    container_name: annuaire-did-nginx
    restart: unless-stopped
    ports:
      - "8889:80"
      # add "443:443" after TLS is in place
    volumes:
      - ./nginx.active_blue.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - annuaire_did_web

networks:
  annuaire_did_web:
    external: true


